color-theme-sanityinc-tomorrow.el
Also noticed that version is marked as {{VERSION}}
=> Update reference to color-theme function names

color-theme-sanityinc-tomorrow.el
[e2wm](https://github.com/kiwanami/emacs-window-manager)
Thanks for following my work!
=> Add faces for e2wm

color-theme-sanityinc-tomorrow.el
(Only tested on tomorrow-blue)
=> Use theme red for flyspell error

color-theme-sanityinc-tomorrow.el
Hi! Thanks for a great port of this color scheme! I found a missing entry for annotation selection in Company mode. Here's a quick fix :)
Cheers!
szw
=> Add company-tooltip-annotation-selection entry

color-theme-sanityinc-tomorrow.el
Blue:
Bright:
Day:
Eighties:
Night:
=> Add missing Anzu faces

color-theme-sanityinc-tomorrow.el
Support for the [Elfeed](https://github.com/skeeto/elfeed) package.
Blue:
Bright:
Day:
Eighties:
Night:
=> Add support for Elfeed

color-theme-sanityinc-tomorrow.el
Support for rcirc, faces matching existing ERC ones.
=> Add rcirc support

color-theme-sanityinc-tomorrow.el
Blue:
Bright:
Day:
Eighties:
Night:
=> Add Info support

color-theme-sanityinc-tomorrow.el
Support for [wgrep](https://github.com/mhayashi1120/Emacs-wgrep).
Blue:
Bright:
Day:
Eighties:
Night:
=> Add wgrep support

color-theme-sanityinc-tomorrow.el
=> Make magit-diff-context more subtle

color-theme-sanityinc-tomorrow.el
=> Fix diff-refine faces

color-theme-sanityinc-tomorrow.el
Blue:
Bright:
Day:
Eighties:
Night:
=> Add Eshell support

color-theme-sanityinc-tomorrow.el
Reverts purcell/color-theme-sanityinc-tomorrow#79
=> Revert "Add form-feed support"

color-theme-sanityinc-tomorrow.el
=> Add Gnus face for extracted buffers

color-theme-sanityinc-tomorrow.el
=> Add ivy-cursor face

color-theme-sanityinc-tomorrow.el
Introduced in `info+-20170729.1141`
=> Add new info+ face

color-theme-sanityinc-tomorrow.el
Support for [Circe](https://github.com/jorgenschaefer/circe).
=> Add Circe support

color-theme-sanityinc-tomorrow.el
Signed-off-by: Julien Masson <massonju.eseo@gmail.com>
=> Add xcscope faces

color-theme-sanityinc-tomorrow.el
This is how it looks with this face set:
=> Add magit-filename face

color-theme-sanityinc-tomorrow.el
=> Theme markup faces

color-theme-sanityinc-tomorrow.el
This is a follow-up for https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/121
I missed a face before, sorry.
=> Add missing nswbuff face

color-theme-sanityinc-tomorrow.el
This is a first attempt at adding support for [transient](https://emacsair.me/2019/02/14/transient-0.1/).
Have a look at the new colours in Magit before merging this, please. If colours are not what you are expecting, I'm happy to change them in order to keep the theme consistent.
=> Theme transient

color-theme-sanityinc-tomorrow.el
=> Theme ztree

color-theme-sanityinc-tomorrow.el
Fixes https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/131
Re: https://github.com/abo-abo/swiper/issues/2034
Thank you @drot and @abo-abo for the help in debugging this.
=> Theme swiper-line-face

color-theme-sanityinc-tomorrow.el
Basic support for [counsel-css](https://github.com/hlissner/emacs-counsel-css).
=> Theme counsel-css

color-theme-sanityinc-tomorrow.el
This PR adds support for [helm-ls-git](https://github.com/emacs-helm/helm-ls-git).
=> Theme helm-ls-git

color-theme-sanityinc-tomorrow.el
=> Remove :height from `helm-source-header`

color-theme-sanityinc-tomorrow.el
See: https://github.com/purcell/color-theme-sanityinc-tomorrow/issues/147#issuecomment-557371849
=> Normalise heights

color-theme-sanityinc-tomorrow.el
This PR adds support for [helm-switch-shell](https://github.com/jamesnvc/helm-switch-shell).
=> Theme helm-switch-shell

color-theme-sanityinc-tomorrow.el
Add support for [helm-rg](https://github.com/cosmicexplorer/helm-rg)
=> Theme helm-rg

color-theme-sanityinc-tomorrow.el
The "usual" trick for extending a face properly.
=> Theme helm-selection-line

color-theme-sanityinc-tomorrow.el
Add support for [mini-modeline](https://github.com/kiennq/emacs-mini-modeline) and [perspective-el](https://github.com/nex3/perspective-el).
=> Add face for mini-modeline and perspective
