purcell/color-theme-sanityinc-tomorrow

README.markdown

http://emacsthemes.caisah.info/sanityinc-tomorrow-themes/ doesn't redirect to http://emacsthemes.com/themes/sanityinc-tomorrow-themes.html.
Also, the 150x150 links are broken but I didn't find the new urls (if they even exist). They are still showing since they are cached by github.

Fix links to emacsthemes.com

---

color-theme-sanityinc-tomorrow.el

This pull request simply changes the `sx-question-mode-content-face` to be the same as `highlight` it makes `sx.el` look prettier (in my opinion)  across the board as be seen in the following screenshots
Blue:
Before:
After:
Night:
Before:
After:

Add faces for sx.el

---

color-theme-sanityinc-tomorrow.el

Small fixes to faces in sx.el that were not previously edited. This is to make all colors in sx.el consistent. Essentially changing all faces that define their own colors to instead use colors defined in the sanity theme.
`sx-question-mode-content-face` still uses the `highlight` color

Fix remaining sx.el faces

---

color-theme-sanityinc-tomorrow.el

Face for the built-in Emacs tooltip implementation.
Blue:
Bright:
Day:
Eighties:
Night:

Add tooltip face

---

color-theme-sanityinc-tomorrow.el

This adds support for [avy](https://github.com/abo-abo/avy) and [ace-window](https://github.com/abo-abo/ace-window). Colors for avy were chosen based on `isearch`.
Blue:
Bright:
Day:
Eighties:
Night:
Ace-window shares the first match color as well as background with avy:

Add avy and ace-window support

---

color-theme-sanityinc-tomorrow.el

Support for the built-in re-builder package, colors taken from `isearch` and `anzu-match` faces.
Blue:
Bright:
Day:
Eighties:
Night:

Add re-builder support

---

color-theme-sanityinc-tomorrow.el

Support for the [debbugs](https://elpa.gnu.org/packages/debbugs.html) package.
Blue:
Bright:
Day:
Eighties:
Night:

Add support for debbugs

---

color-theme-sanityinc-tomorrow.el

Support for the [NeoTree](https://github.com/jaypei/emacs-neotree) package.
Blue:
Bright:
Day:
Eighties:
Night:

Add NeoTree support

---

color-theme-sanityinc-tomorrow.el

This adds support for the built-in ruler-mode.
Blue:
Bright:
Day:
Eighties:
Night:

Ruler mode support

---

color-theme-sanityinc-tomorrow.el

Built-in `hi-lock-mode`, made to match theme colors. Last match uses an oversized font by default so I just reduced its size to `1.4`.
Blue:
Bright:
Day:
Eighties:
Night:

Support for hi-lock mode

---

color-theme-sanityinc-tomorrow.el

Part of the [emacs-async](https://github.com/jwiegley/emacs-async) package, this adds faces for the mode-line messages.

Support for dired-async

---

color-theme-sanityinc-tomorrow.el

Just a couple of additions, added `whitespace-big-indent` and made `trailing-whitespace` as same as `whitespace-trailing`. Calendar already inherits everything except two faces so I added those. Lastly, I'm currently testing `wgrep` faces so I'll push those after this. Thank you for the patience in merging these commits. :smiley:

Add missing Whitespace face, add missing Calendar faces

---

color-theme-sanityinc-tomorrow.el

As you mentioned earlier no harsh backgrounds.
Before:
After:

Make diff-refine* faces more subtle

---

color-theme-sanityinc-tomorrow.el

Instead of using a red background just use a red foreground.

Avoid harsh background in wdired as well

---

color-theme-sanityinc-tomorrow.el

This adds Speedbar support, mostly a 1:1 color translation.
Blue:
Bright:
Day:
Eighties:
Night:

Add Speedbar support

---

color-theme-sanityinc-tomorrow.el

Support for [form-feed](https://github.com/wasamasa/form-feed), the page break line is white by default so I changed it to comment color.

Add form-feed support

---

color-theme-sanityinc-tomorrow.el

Modeline border was removed in 38aa7fefc (Apr 10, 2016). This adds
back the border used then for the inactive mode line for both active
and inactive modelines. This adds a subtle border which helps the eye
distinguish the mode line from text while still looking minimal.

Add some subtle contrast to modeline

---

color-theme-sanityinc-tomorrow.el

helm-visible-mark uses green blackground by default, it doesn't look very well with sanityinc-tomorrow-eighties.

Add helm-visible-mark

---

color-theme-sanityinc-tomorrow.el

Just a couple of faces to make `git-timemachine` match the theme.

Add faces for git-timemachine

---

color-theme-sanityinc-tomorrow.el

`isearch-lazy-highlight-face` has been removed, and elsewhere in the theme it's already been [replaced with `lazy-highlight`](https://github.com/purcell/color-theme-sanityinc-tomorrow/commit/c42554ce5dbc7a7660ee0a8f47861c06634b9b61); this fixes one spot where `anzu-replace-highlight` was inheriting from the old, now-nonexistent face.

Make anzu-replace-highlight inherit lazy-highlight

---

color-theme-sanityinc-tomorrow.el

This how it looks before my patch:
And this is after:
Nothing really major. :)

Theme outline-minor-faces

---

color-theme-sanityinc-tomorrow.el

See: https://github.com/joostkremers/nswbuff
Before:
After:

Theme nswbuff

---

color-theme-sanityinc-tomorrow.el

Support for [stripe-buffer](https://github.com/sabof/stripe-buffer).
Without this PR it looks like this:
With this PR it looks like this:

Theme stripe-buffer

---

color-theme-sanityinc-tomorrow.el

We don't add git-gutter-fringe+ because it inherits from git-gutter+

add git-gutter+

---

color-theme-sanityinc-tomorrow.el

Changed Sly's faces for notes, style-warnings and warnings from *foreground* to *underline*.
Hi,
I know it can be very subjective and don't know if subtle was the desired effect, but I've found out that using foreground in Sly's faces for notes, style-warnings and warnings makes them not stand out, in particular notes.
In my opinion using underline isn't too much "garish" but feel free to reject this PR if you don't like the result.
Andrea

Changed Sly faces from foreground to underline

---

color-theme-sanityinc-tomorrow.el

Hi,
I am trying to theme `swiper-isearch-current-match`, in order to distinguish matches on the same line. I did something similar for `zenburn-emacs`, but I guess I am missing something here because I don't see the new face applied as expected.
What did i do wrong? :)

Theme swiper-isearch-current-match

---

color-theme-sanityinc-tomorrow.el

I added faces for [bm](https://github.com/joodland/bm) and a missing face for `markup`.
Let me know if you need me to change anything.

Theme bm and markup-code-face

---

color-theme-sanityinc-tomorrow.el

This PR aims to support [fold-this](https://github.com/magnars/fold-this.el).
Before:
After:

Theme fold-this

---

color-theme-sanityinc-tomorrow.el

This PR adds support for `kaocha-runner` messages, following https://github.com/magnars/kaocha-runner.el/pull/3.

Theme kaocha-runner

---

color-theme-sanityinc-tomorrow.el

I added support for https://github.com/vapniks/syslog-mode
An example:

Theme syslog-mode

---

color-theme-sanityinc-tomorrow.el

This PR extends `bm` faces to EOL.
For further comments on `:extend`, see: https://github.com/purcell/color-theme-sanityinc-tomorrow/issues/140

Extend bm faces

---

color-theme-sanityinc-tomorrow.el

This is a first run at tackling https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/144#issuecomment-553648885
Please do not merge this until I am clear about the following doubts:
- `tab-bar`: does it make sense to make it `1.2`? Probably the point `1.1` was it to make slightly different but still pleasant? I don't use this feature, so I want to be sure I'm not altering something already good as it is.
- what about the followings?
```emacs-lisp
(info-title-1 (:weight bold :height 1.6))
(info-title-2 (:weight bold :height 1.4))
(info-title-3 (:weight bold :height 1.2))
(info-title-4 (:weight bold))
```
If we use only to possible values for `:height`, how can we distinguish `info-title-3` from `info-title-4`?
- what about these?
```emacs-lisp
(sx-question-list-answers (:height …
```

Normalise :height values

---

color-theme-sanityinc-tomorrow.el

Minor fix to the previous `helm-rg` theming.

Fix helm-rg-colon-separator-ripgrep-output-face

---

color-theme-sanityinc-tomorrow.el

Orange is the colour of Helm headers, so it's best to not use it for candidates to avoid confusion.

Try to avoid using orange

---

color-theme-sanityinc-tomorrow.el

This PR adds support for [emacs-libvterm](https://github.com/akermu/emacs-libvterm).
I followed these guidelines: https://github.com/akermu/emacs-libvterm#colors

Theme vterm

---

color-theme-sanityinc-tomorrow.el

This PR adds support for [define-it](https://github.com/jcs-elpa/define-it).

Theme define-it

---

color-theme-sanityinc-tomorrow.el

Apparently in `web-mode` there is a face `web-mode-html-tag-bracket-face` for the coloring of tag brackets. Without setting it, the brackets by default will have the same color as the background, making them invisible. Adding this line fixes the issue.
Also see a similar issue in https://github.com/oneKelvinSmith/monokai-emacs/issues/102 which had the same fix.

Fix coloring of HTML tag brackets in web-mode

---

color-theme-sanityinc-tomorrow.el

Otherwise, [the font size for `display-line-numbers-mode` does not change with text scale](https://emacs.stackexchange.com/questions/74507/constant-font-size-in-display-line-numbers-mode-when-zooming-in-and-out).
text scale is when you do `M-x text-scale-adjust (C-x C-0)`, `C-<wheel-up/down>` or `<pinch>`.
<details>
<summary>Extra information</summary>
My Emacs version: GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.40, cairo version 1.18.0)
</details>

Face `line-number` should inherit from default

---

color-theme-sanityinc-tomorrow.el

Add support for window-tool-bar which has been added to Emacs 30.

Add support for window-tool-bar
